##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [2]:
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
b=np.array(list_temperature)
print(b)
type(b)

[3.04 1.65 5.76 1.66 1.54 4.69 2.68]


numpy.ndarray

In [3]:
a=np.array( [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68] )
a

array([3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [8]:
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
students_weight=np.array(weights)
students_weight[students_weight>68]

array([74.2, 85. , 74. , 70.5, 86. , 82. ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [9]:
np.random.randint(20,40,10)

array([28, 36, 29, 31, 20, 25, 26, 35, 39, 38])

In [ ]:
it is possible if we save this random integers into a memory location

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [11]:
np.arange(1,6)**5

array([   1,   32,  243, 1024, 3125], dtype=int32)

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [12]:
np.arange(51,100,2)

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [26]:
A = np.array([[1, 4, 8], [5, 7, 3], [9, 14, 2]])
A.sum(axis=0)

array([15, 25, 13])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [15]:
a=np.array([42, 87, 90, 14, 32, 75, 61, 80, 92])
a%8

array([2, 7, 2, 6, 0, 3, 5, 0, 4], dtype=int32)

<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [2]:
import numpy as np
a=np.arange(1,21)
b=a.reshape(4,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [60]:
b[1]

array([ 6,  7,  8,  9, 10])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [10]:
prices_monday =np.array( [10, 30, 50, 60, 90])

prices_tuesday = np.array([50, 20, 80, 125, 10, 70])


np.intersect1d(prices_monday,prices_tuesday)


array([10, 50])

In [18]:
prices_monday =np.array( [10, 30, 50, 60, 90])

prices_tuesday = np.array([50, 20, 80, 125, 10, 70])
c=[]
for i in prices_monday:
    for j in prices_tuesday:
        if i==j:
            c.append(i)
print(c)
            

[10, 50]


In [20]:
[i for i in prices_monday for j in prices_tuesday if i==j ]

[10, 50]

In [25]:
[i for i in prices_monday if i in prices_tuesday]

[10, 50]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [28]:
weights = np.array([57, 69, 54, 65 ,71, 62, 56])
heights = np.array([1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53])
BMI= weights/heights**2
BMI

array([22.54657648, 22.53061224, 19.59645812, 21.46915048, 26.39797739,
       20.9572742 , 23.922423  ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [32]:
array1 = np.array([[[3, 4], [8, 2],[5, 9]]])i
new_array=np.insert(array1,obj=3,values=[5,7],axis=1)

new_array

array([[[3, 4],
        [8, 2],
        [5, 9],
        [5, 7]]])


12. Write a code to print the identity matrix of order 5
                

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [41]:
M =np.array( [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]])
np.transpose(M)


array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

In [42]:
M.T

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [9]:
A1 =np.array( [[5, 9], [7, 6]])

A2 = np.array([[8,-7], [0,4]])
np.stack([A1,A2],axis=0)

array([[[ 5,  9],
        [ 7,  6]],

       [[ 8, -7],
        [ 0,  4]]])

In [34]:
A1 =np.array( [[5, 9], [7, 6]])

A2 = np.array([[8,-7], [0,4]])
np.vstack([A2,A1])

array([[ 8, -7],
       [ 0,  4],
       [ 5,  9],
       [ 7,  6]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [38]:
A1 =np.array( [[-81, 75, 40], [27, 67, 52]])

A2 =np.array( [[15, 54], [39, 56]])
np.hstack([A2,A1])

array([[ 15,  54, -81,  75,  40],
       [ 39,  56,  27,  67,  52]])

<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [51]:
A = np.array([[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]])
print(A)
np.vsplit(A,3)

[[ 4  7]
 [ 2 -3]
 [ 8  1]
 [ 0  9]
 [ 5 -1]
 [ 8  3]]


[array([[ 4,  7],
        [ 2, -3]]),
 array([[8, 1],
        [0, 9]]),
 array([[ 5, -1],
        [ 8,  3]])]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [54]:
B = np.array([[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]])
print(B)
np.hsplit(B,2)


[[ 8  7  0  9]
 [ 2 -3  5 10]
 [ 8  5 -1  3]]


[array([[ 8,  7],
        [ 2, -3],
        [ 8,  5]]),
 array([[ 0,  9],
        [ 5, 10],
        [-1,  3]])]

<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [55]:
L1 = np.array( [45, 67, 56, 71, 54, 62, 56])

L2 = np.array([21, 52, 64, 10, 49, 74, 26])
for data in zip(L1,L2):
    print(data)


(45, 21)
(67, 52)
(56, 64)
(71, 10)
(54, 49)
(62, 74)
(56, 26)


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [57]:
numbers = np.array([6, 5, 3, 15])
for x in numbers:
    print((2*x-1)/(x+5))

1.0
0.9
0.625
1.45


2. Find the minimum value along each of the rows
Create a 2D Numpy array from list of lists
num_array = np.array([[110, 102, 183],
                 [140, 175, 106],
                 [170, 195, 117],
                 [192, 140, 195]])

In [21]:
num_array = np.array([[110, 102, 183],
                 [140, 175, 106],
                 [170, 195, 117],
                 [192, 140, 195]])
num_array.min(axis=1)

array([102, 106, 117, 140])

In [23]:
num_array = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])
len(num_array)


13

In [24]:
num_array[1:12:2]=-2
num_array

array([ 0, -2, 42, -2, 34, -2, 26, -2, 38, -2, 65, -2, 76])

In [26]:
num_array1 = np.array([1,2,3,2,3,4,3,4,5,6])

num_array2 = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(num_array1==num_array2 )

(array([1, 3, 5, 7], dtype=int64),)

In [ ]:
9. Reverse each of the rows of the 2D array
Use the array given below:

num_array1 = np.arange(16).reshape(4,4)
num_array1 = np.arange(16).reshape(4,4)
print(num_array1)
reverse_array=np.flip(num_array1)
reverse_array

In [ ]:
Swap row 1 and row 2 in the given array
Use the array given below:

   num_array1 = np.arange(9).reshape(3,3)
num_array1 = np.arange(9).reshape(3,3)
print(num_array1)
​
num_array1[[0,1], :]=num_array1[[1,0], :]
​
​
num_array1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])